# Generated by Django 4.2.1 on 2023-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('list_of_followers', models.JSONField()),
                ('list_of_following', models.JSONField()),
                ('list_of_events', models.JSONField()),
            ],
        ),
    ]
