# Generated by Django 4.2.1 on 2023-07-25 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=200)),
                ('event_description', models.TextField(blank=True)),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=25, unique=True)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('user_type', models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=50)),
                ('user_privacy', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=50)),
                ('attending_events', models.ManyToManyField(blank=True, related_name='attending', to='home.event')),
                ('created_events', models.ManyToManyField(blank=True, related_name='creators', to='home.event')),
                ('list_of_followers', models.ManyToManyField(blank=True, related_name='following', to='home.user')),
                ('list_of_following', models.ManyToManyField(blank=True, related_name='followers', to='home.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='list_of_attendees',
            field=models.ManyToManyField(blank=True, to='home.user'),
        ),
    ]
