# Generated by Django 4.2.1 on 2023-05-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_username_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='list_of_events',
            field=models.JSONField(max_length=3),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('list_of_attendees', models.JSONField(max_length=8)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
