# Generated by Django 4.2.1 on 2023-05-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_list_of_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='list_of_events',
            field=models.JSONField(default=list, max_length=3),
        ),
    ]
