# Generated by Django 4.2.1 on 2023-05-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='list_of_events',
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.user'),
        ),
    ]
