# Generated by Django 4.2.1 on 2023-08-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_profile_pic_alter_user_user_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50),
        ),
    ]
