# Generated by Django 4.2.1 on 2023-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_list_of_events_alter_event_creation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], default='individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='list_of_attendees',
            field=models.JSONField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_of_followers',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_of_following',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
