# Generated by Django 4.2.1 on 2024-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_location_event_location_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='received_follow_requests', to='home.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='requesting_users',
            field=models.ManyToManyField(blank=True, related_name='sent_follow_request', to='home.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50),
        ),
    ]
