# Generated by Django 4.2.1 on 2023-06-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='list_of_followers',
        ),
        migrations.AlterField(
            model_name='user',
            name='list_of_following',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='list_of_followers',
            field=models.ManyToManyField(related_name='following', to='home.user'),
        ),
    ]
