# Generated by Django 4.2.1 on 2023-06-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_user_list_of_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='list_of_following',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], default='individual', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='list_of_following',
            field=models.ManyToManyField(related_name='followers', to='home.user'),
        ),
    ]
