# Generated by Django 4.2.1 on 2024-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_user_user_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follower', 'Follower'), ('request', 'Follow Request'), ('event_registration', 'Event Registration')], max_length=25),
        ),
    ]
