# Generated by Django 4.2.1 on 2024-08-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notif', to='home.event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privacy',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=50),
        ),
    ]
