# Generated by Django 4.2.1 on 2023-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_user_list_of_following_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='list_of_attendees',
        ),
        migrations.AlterField(
            model_name='user',
            name='list_of_followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='home.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_of_following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='home.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='list_of_attendees',
            field=models.ManyToManyField(blank=True, max_length=8, to='home.user'),
        ),
    ]
