# Generated by Django 4.2.1 on 2023-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_event_date_remove_event_list_of_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=100),
        ),
    ]
