# Generated by Django 4.2.1 on 2024-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_user_blocked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='user_subscriptions', to='home.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Follow Request'), ('event_registration', 'Event Registration'), ('follower', 'Follower')], max_length=25),
        ),
    ]
