# Generated by Django 4.2.1 on 2023-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_event_date_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_of_events',
            field=models.ManyToManyField(blank=True, related_name='creators', to='home.event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], default='individual', max_length=100),
        ),
    ]
