# Generated by Django 4.2.1 on 2024-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_registration', 'Event Registration'), ('request', 'Follow Request'), ('follower', 'Follower')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
