# Generated by Django 4.2.1 on 2023-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_list_of_events_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='list_of_events',
            new_name='created_events',
        ),
        migrations.AddField(
            model_name='user',
            name='attending_events',
            field=models.ManyToManyField(blank=True, related_name='attending', to='home.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='list_of_attendees',
            field=models.ManyToManyField(blank=True, to='home.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=100),
        ),
    ]
