# Generated by Django 4.2.1 on 2023-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_list_of_events_user_created_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], default='individual', max_length=100),
        ),
    ]
