# Generated by Django 4.2.1 on 2024-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_user_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Follow Request'), ('follower', 'Follower'), ('event_registration', 'Event Registration')], max_length=25),
        ),
    ]
