# Generated by Django 4.2.1 on 2023-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=100),
        ),
    ]
