# Generated by Django 4.2.1 on 2025-02-05 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_notification_notification_type_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentioned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_comments', to='home.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Follow Request'), ('follower', 'Follower'), ('event_registration', 'Event Registration')], max_length=25),
        ),
    ]
