# Generated by Django 4.2.1 on 2025-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_conversation_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Follow Request'), ('event_registration', 'Event Registration'), ('follower', 'Follower')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual')], default='individual', max_length=50),
        ),
    ]
