# Generated by Django 4.2.1 on 2025-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follower', 'Follower'), ('event_registration', 'Event Registration'), ('request', 'Follow Request')], max_length=25),
        ),
    ]
