# Generated by Django 4.2.1 on 2025-03-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Follow Request'), ('event_registration', 'Event Registration'), ('follower', 'Follower')], max_length=25),
        ),
    ]
